# Generated by Django 5.2.8 on 2026-01-04 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("duration_days", models.PositiveIntegerField()),
                ("max_exam_number", models.PositiveIntegerField(default=0)),
                ("ai_assistance_enabled", models.BooleanField(default=False)),
                ("personalized_feedback_enabled", models.BooleanField(default=False)),
                ("full_road_sign_quiz", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
                (
                    "unlimited_practice",
                    models.BooleanField(
                        default=False, help_text="Unlimited attempts on exams"
                    ),
                ),
                (
                    "offline_access",
                    models.BooleanField(
                        default=True, help_text="Allow offline exam sync"
                    ),
                ),
                ("priority_support", models.BooleanField(default=False)),
                ("ad_free", models.BooleanField(default=True)),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, help_text="True if this is the free tier"
                    ),
                ),
                (
                    "exams",
                    models.ManyToManyField(
                        blank=True, related_name="tiers", to="core.exam"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Tier",
                "verbose_name_plural": "Subscription Tiers",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "tg_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tg_data", models.JSONField(blank=True, default=dict)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_users",
                        to="users.subscription",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="users.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionTierTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="users.subscriptiontier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Tier Translation",
                "verbose_name_plural": "Subscription Tier Translations",
                "unique_together": {("tier", "language")},
            },
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["tg_id", "expiry_date"], name="users_userp_tg_id_97319b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user_profile", "tier"], name="users_subsc_user_pr_ad0464_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user_profile", "is_active"],
                name="users_subsc_user_pr_0f3369_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["expiry_date"], name="users_subsc_expiry__bfb469_idx"
            ),
        ),
    ]
