# Generated by Django 5.2.8 on 2026-01-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
