# Generated by Django 5.2.8 on 2026-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="exams",
            field=models.ManyToManyField(
                blank=True, related_name="tiers", to="core.exam"
            ),
        ),
    ]
