# Generated by Django 5.2.8 on 2025-12-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptiontiertranslation",
            options={
                "verbose_name": "Subscription Tier Translation",
                "verbose_name_plural": "Subscription Tier Translations",
            },
        ),
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subscriptiontier",
            name="name",
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Display Order"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiontiertranslation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptiontiertranslation",
            unique_together={("tier", "language")},
        ),
    ]
