# Generated by Django 5.2.8 on 2025-12-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_subscriptiontiertranslation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="True if this is the free tier subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="ad_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="offline_access",
            field=models.BooleanField(
                default=True, help_text="Allow offline exam sync"
            ),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="priority_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="unlimited_practice",
            field=models.BooleanField(
                default=False, help_text="Unlimited attempts on exams"
            ),
        ),
    ]
