# Generated by Django 5.2.8 on 2026-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription_created_at_subscription_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("am", "Amharic"),
                    ("ti", "Tigrigna"),
                    ("or", "Afan Oromo"),
                ],
                default="am",
                max_length=10,
            ),
        ),
    ]
