# Generated by Django 5.2.8 on 2025-12-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription_is_free_subscriptiontier_ad_free_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_free",
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="is_free",
            field=models.BooleanField(
                default=False, help_text="True if this is the free tier"
            ),
        ),
    ]
