# Generated by Django 5.2.8 on 2026-03-18 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_preferred_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="users_userp_tg_id_97319b_idx",
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["expiry_date"], name="users_userp_expiry__b5671b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["tg_id"], name="users_userp_tg_id_d3b387_idx"),
        ),
    ]
