# Generated by Django 5.2.8 on 2025-12-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_subscription_is_free_subscriptiontier_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="popular",
            field=models.BooleanField(default=False),
        ),
    ]
