# Generated by Django 5.2.8 on 2025-12-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscriptiontier_popular"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user_profile", "tier", "is_active")},
        ),
    ]
