# Generated by Django 5.2.8 on 2025-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_subscription_unique_together"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="subscription",
            name="users_subsc_user_pr_a76397_idx",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user_profile", "tier"], name="users_subsc_user_pr_ad0464_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user_profile", "is_active"],
                name="users_subsc_user_pr_0f3369_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["expiry_date"], name="users_subsc_expiry__bfb469_idx"
            ),
        ),
    ]
