# Generated by Django 5.2.8 on 2025-12-20 01:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correct Answer"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BundleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Bundle Name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Bundle Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "exam_quota",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of exam attempts included (0 = unlimited)",
                        verbose_name="Exam Attempts",
                    ),
                ),
                (
                    "total_chat_quota",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total AI chat messages included (0 = unlimited)",
                        verbose_name="Total Chat Quota",
                    ),
                ),
                (
                    "daily_chat_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Daily limit for AI chat messages (0 = unlimited)",
                        verbose_name="Daily Chat Limit",
                    ),
                ),
                (
                    "search_quota",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of searchable questions (0 = unlimited)",
                        verbose_name="Search Quota",
                    ),
                ),
                (
                    "has_unlimited_road_sign_quiz",
                    models.BooleanField(
                        default=False,
                        help_text="Unlimited access to road sign quizzes",
                        verbose_name="Unlimited Road Sign Quiz",
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        help_text="Number of days the bundle is valid for",
                        verbose_name="Validity (days)",
                    ),
                ),
                (
                    "price_etb",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Price (ETB)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bundle Definition",
                "verbose_name_plural": "Bundle Definitions",
                "ordering": ["order", "price_etb"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, help_text="A valid logo url", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=150.0,
                        help_text="Amount in ETB for Pro subscription",
                        max_digits=10,
                        verbose_name="Required Amount",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("IT", "Image to Text"),
                            ("TI", "Text to Image"),
                            ("TT", "Text to Text"),
                        ],
                        default="IT",
                        max_length=2,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Premium Question"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], default=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Category",
                "verbose_name_plural": "Question Categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadSign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal code for the road sign",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="road_signs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Road Sign",
                "verbose_name_plural": "Road Signs",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoadSignCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Sign Category",
                "verbose_name_plural": "Road Sign Categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="AIChatHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chat History",
                "verbose_name_plural": "AI Chat Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("is_premium", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="core.articlecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BundleOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Order Amount (ETB)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("payment_verified", "Payment Verified"),
                            ("insufficient_funds", "Insufficient Funds"),
                            ("completed", "Order Completed"),
                            ("cancelled", "Order Cancelled"),
                            ("expired", "Order Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference Number"
                    ),
                ),
                (
                    "verified_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Verified Amount",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.bundledefinition",
                        verbose_name="Selected Bundle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle Order",
                "verbose_name_plural": "Bundle Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("timed_out", "Timed Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "time_taken",
                    models.IntegerField(
                        blank=True, help_text="Time taken in seconds", null=True
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Session",
                "verbose_name_plural": "Exam Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "time_spent",
                    models.FloatField(
                        blank=True, help_text="Time spent in seconds", null=True
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.answerchoice",
                    ),
                ),
                (
                    "exam_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.examsession",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("exam_session", "question")},
            },
        ),
        migrations.CreateModel(
            name="OrderBundleSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=200, verbose_name="Suggestion Reason"),
                ),
                (
                    "order_score",
                    models.FloatField(default=0.0, verbose_name="Recommendation Score"),
                ),
                (
                    "bundle_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundledefinition",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundleorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_score"],
                "unique_together": {("order", "bundle_definition")},
            },
        ),
        migrations.AddField(
            model_name="bundleorder",
            name="suggested_bundles",
            field=models.ManyToManyField(
                related_name="suggested_in_orders",
                through="core.OrderBundleSuggestion",
                to="core.bundledefinition",
                verbose_name="Suggested Bundles",
            ),
        ),
        migrations.AddField(
            model_name="bundleorder",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bundle_orders",
                to="core.paymentmethod",
                verbose_name="Payment Method",
            ),
        ),
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="Media URL"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanation",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation",
                "verbose_name_plural": "Explanations",
            },
        ),
        migrations.AddField(
            model_name="examsession",
            name="questions",
            field=models.ManyToManyField(
                through="core.ExamQuestion", to="core.question"
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="core.questioncategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="road_sign_context",
            field=models.ForeignKey(
                blank=True,
                help_text="The road sign this question is about",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="core.roadsign",
                verbose_name="Associated Road Sign",
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="road_sign_option",
            field=models.ForeignKey(
                blank=True,
                help_text="For Text→Image questions: the road sign image option",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_choices",
                to="core.roadsign",
                verbose_name="Road Sign Option",
            ),
        ),
        migrations.AddField(
            model_name="roadsign",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="road_signs",
                to="core.roadsigncategory",
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="RoadSignCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.roadsigncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Sign Category Translation",
                "verbose_name_plural": "Road Sign Category Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="RoadSignTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "meaning",
                    models.CharField(
                        help_text="Concise meaning for quick reference",
                        max_length=500,
                        verbose_name="Meaning",
                    ),
                ),
                (
                    "detailed_explanation",
                    models.TextField(
                        help_text="Rich content including HTML, images, GIFs, video/audio URLs for complete learning",
                        verbose_name="Detailed Explanation",
                    ),
                ),
                (
                    "road_sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.roadsign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Sign Translation",
                "verbose_name_plural": "Road Sign Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="UserBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Purchase Date"
                    ),
                ),
                ("expiry_date", models.DateTimeField(verbose_name="Expiry Date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "exams_remaining",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Exams Remaining"
                    ),
                ),
                (
                    "chats_remaining",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Chats Remaining"
                    ),
                ),
                (
                    "search_remaining",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Search Remaining"
                    ),
                ),
                (
                    "total_chats_consumed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Chats Consumed"
                    ),
                ),
                (
                    "last_chat_reset",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Last Chat Reset",
                    ),
                ),
                (
                    "daily_chats_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Daily Chats Used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_bundles",
                        to="core.bundledefinition",
                        verbose_name="Bundle Definition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Bundle",
                "verbose_name_plural": "User Bundles",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="ResourceTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Bundle Purchase"),
                            ("consume", "Resource Consumption"),
                            ("refund", "Resource Refund"),
                            ("reset", "Daily Reset"),
                            ("expiry", "Bundle Expiry"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exam", "Exam Attempt"),
                            ("chat", "AI Chat"),
                            ("search", "Search"),
                            ("road_sign", "Road Sign Quiz"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Resource Type",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "exams_before",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Exams Before"
                    ),
                ),
                (
                    "exams_after",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Exams After"
                    ),
                ),
                (
                    "chats_before",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Chats Before"
                    ),
                ),
                (
                    "chats_after",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Chats After"
                    ),
                ),
                (
                    "search_before",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Search Before"
                    ),
                ),
                (
                    "search_after",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Search After"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "user_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.userbundle",
                        verbose_name="User Bundle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Transaction",
                "verbose_name_plural": "Resource Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BundlePurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Amount Paid (ETB)",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference Number"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Transaction ID"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bundle_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="core.bundledefinition",
                        verbose_name="Bundle Definition",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_purchase",
                        to="core.bundleorder",
                        verbose_name="Source Order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundle_purchases",
                        to="core.paymentmethod",
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "user_bundle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_record",
                        to="core.userbundle",
                        verbose_name="Resulting User Bundle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bundle Purchase",
                "verbose_name_plural": "Bundle Purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bundleorder",
            name="resulting_bundle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="core.userbundle",
                verbose_name="Resulting Bundle",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telegram_data", models.JSONField(blank=True, default=dict)),
                (
                    "offline_cache_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "offline_cache_generated",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("total_exam_attempts", models.PositiveIntegerField(default=0)),
                ("total_practice_questions", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("highest_exam_score", models.FloatField(default=0)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "exam_time_limit",
                    models.IntegerField(
                        default=1800, help_text="Exam time limit in seconds"
                    ),
                ),
                ("questions_per_exam", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_users",
                        to="core.userbundle",
                        verbose_name="Active Bundle",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "time_taken",
                    models.FloatField(
                        blank=True, help_text="Time taken in seconds", null=True
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="core.question",
                    ),
                ),
                (
                    "selected_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_selections",
                        to="core.answerchoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress",
            },
        ),
        migrations.CreateModel(
            name="AnswerChoiceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Text")),
                (
                    "answer_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.answerchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice Translation",
                "verbose_name_plural": "Answer Choice Translations",
                "ordering": ["language"],
                "unique_together": {("answer_choice", "language")},
            },
        ),
        migrations.CreateModel(
            name="ExplanationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(verbose_name="Detail")),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.explanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation Translation",
                "verbose_name_plural": "Explanation Translations",
                "ordering": ["language"],
                "unique_together": {("explanation", "language")},
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("account_details", models.TextField(verbose_name="Account Details")),
                ("instruction", models.TextField(verbose_name="Instruction")),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method Translation",
                "verbose_name_plural": "Payment Method Translations",
                "ordering": ["language"],
                "unique_together": {("payment_method", "language")},
            },
        ),
        migrations.CreateModel(
            name="QuestionCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.questioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Category Translation",
                "verbose_name_plural": "Question Category Translations",
                "ordering": ["language"],
                "unique_together": {("category", "language")},
            },
        ),
        migrations.CreateModel(
            name="QuestionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Translation",
                "verbose_name_plural": "Question Translations",
                "ordering": ["language"],
                "unique_together": {("question", "language")},
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["road_sign_context"], name="core_questi_road_si_fe96d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_premium", "difficulty"],
                name="core_questi_is_prem_62b4a8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answerchoice",
            unique_together={("question", "order")},
        ),
        migrations.AddIndex(
            model_name="roadsign",
            index=models.Index(
                fields=["category"], name="core_roadsi_categor_f3eec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsign",
            index=models.Index(fields=["code"], name="core_roadsi_code_ea8443_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roadsigncategorytranslation",
            unique_together={("category", "language")},
        ),
        migrations.AddIndex(
            model_name="roadsigntranslation",
            index=models.Index(
                fields=["road_sign", "language"], name="core_roadsi_road_si_42c138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsigntranslation",
            index=models.Index(fields=["name"], name="core_roadsi_name_34697b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roadsigntranslation",
            unique_together={("road_sign", "language")},
        ),
        migrations.AddIndex(
            model_name="userbundle",
            index=models.Index(
                fields=["user", "is_active", "expiry_date"],
                name="core_userbu_user_id_2ba52e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userbundle",
            index=models.Index(
                fields=["expiry_date"], name="core_userbu_expiry__418726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbundle",
            index=models.Index(
                fields=["last_chat_reset"], name="core_userbu_last_ch_5187bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcetransaction",
            index=models.Index(
                fields=["user", "created_at"], name="core_resour_user_id_38d46a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcetransaction",
            index=models.Index(
                fields=["transaction_type", "resource_type"],
                name="core_resour_transac_e3cd7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcetransaction",
            index=models.Index(
                fields=["user_bundle"], name="core_resour_user_bu_69d9f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundlepurchase",
            index=models.Index(
                fields=["user", "payment_status"], name="core_bundle_user_id_a28b88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundlepurchase",
            index=models.Index(
                fields=["payment_status", "created_at"],
                name="core_bundle_payment_e86dc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bundlepurchase",
            index=models.Index(
                fields=["reference_number"], name="core_bundle_referen_054df5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleorder",
            index=models.Index(
                fields=["user", "status"], name="core_bundle_user_id_872008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleorder",
            index=models.Index(
                fields=["status", "expires_at"], name="core_bundle_status_4ca877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bundleorder",
            index=models.Index(
                fields=["reference_number"], name="core_bundle_referen_2e839e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["telegram_id"], name="core_userpr_telegra_44be81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["active_bundle"], name="core_userpr_active__a71e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "created_at"], name="core_userpr_user_id_fbadee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["session_id"], name="core_userpr_session_e1a678_idx"
            ),
        ),
    ]
