# Generated by Django 5.2.8 on 2025-12-23 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correct Answer"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice",
                "verbose_name_plural": "Answer Choices",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("difficulty", models.CharField(max_length=50)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("question_count", models.PositiveIntegerField(default=50)),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70, help_text="Passing percentage"
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
            },
        ),
        migrations.CreateModel(
            name="ExamTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Explanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="Media URL"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Explanation",
                "verbose_name_plural": "Explanations",
            },
        ),
        migrations.CreateModel(
            name="ExplanationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(verbose_name="Detail")),
            ],
            options={
                "verbose_name": "Explanation Translation",
                "verbose_name_plural": "Explanation Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="questions/",
                        verbose_name="image",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("IT", "Image to Text"),
                            ("TI", "Text to Image"),
                            ("TT", "Text to Text"),
                        ],
                        default="IT",
                        max_length=2,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        default="medium", max_length=50, verbose_name="Difficulty"
                    ),
                ),
                ("is_premium", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question Category",
                "verbose_name_plural": "Question Categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Question Category Translation",
                "verbose_name_plural": "Question Category Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="QuestionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
            ],
            options={
                "verbose_name": "Question Translation",
                "verbose_name_plural": "Question Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="RoadSign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal code for the road sign",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="road_signs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Road Sign",
                "verbose_name_plural": "Road Signs",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoadSignCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Sign Category",
                "verbose_name_plural": "Road Sign Categories",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadSignCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Road Sign Category Translation",
                "verbose_name_plural": "Road Sign Category Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="RoadSignTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "meaning",
                    models.CharField(
                        help_text="Concise meaning for quick reference",
                        max_length=500,
                        verbose_name="Meaning",
                    ),
                ),
                (
                    "detailed_explanation",
                    models.TextField(
                        help_text="Rich content including HTML, images, GIFs, video/audio URLs for complete learning",
                        verbose_name="Detailed Explanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Road Sign Translation",
                "verbose_name_plural": "Road Sign Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="AnswerChoiceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Text")),
                (
                    "answer_choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="core.answerchoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Choice Translation",
                "verbose_name_plural": "Answer Choice Translations",
                "ordering": ["language"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("score", models.FloatField(null=True)),
                ("is_passed", models.BooleanField(null=True)),
                ("raw_answers_json", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Attempt",
                "verbose_name_plural": "Exam Attempts",
            },
        ),
    ]
