# Generated by Django 5.2.8 on 2025-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundledefinition",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
    ]
