# Generated by Django 5.2.8 on 2026-01-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="examtranslation",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.exam",
            ),
        ),
        migrations.AddField(
            model_name="explanationtranslation",
            name="explanation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.explanation",
            ),
        ),
        migrations.AddField(
            model_name="explanation",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="explanation",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(related_name="exams", to="core.question"),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="core.questioncategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="questioncategorytranslation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.questioncategory",
            ),
        ),
        migrations.AddField(
            model_name="questiontranslation",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="associated_road_sign",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to road sign if this question is specifically about one; use for sign metadata/translations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="core.roadsign",
                verbose_name="Associated Road Sign",
            ),
        ),
        migrations.AddField(
            model_name="answerchoice",
            name="road_sign_option",
            field=models.ForeignKey(
                blank=True,
                help_text="For Text→Image questions: the road sign image option",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_choices",
                to="core.roadsign",
                verbose_name="Road Sign Option",
            ),
        ),
        migrations.AddField(
            model_name="roadsign",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="road_signs",
                to="core.roadsigncategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="roadsigncategorytranslation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.roadsigncategory",
            ),
        ),
        migrations.AddField(
            model_name="roadsigntranslation",
            name="road_sign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="core.roadsign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answerchoicetranslation",
            unique_together={("answer_choice", "language")},
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["user_profile", "status"], name="core_examat_user_pr_08c013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["deleted_at"], name="core_examat_deleted_f5c08b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examtranslation",
            unique_together={("exam", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="explanationtranslation",
            unique_together={("explanation", "language")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["is_free"], name="core_exam_is_free_e43e41_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="questioncategorytranslation",
            unique_together={("category", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="questiontranslation",
            unique_together={("question", "language")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["associated_road_sign"], name="core_questi_associa_abc12d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="core_questi_difficu_10c222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["category"], name="core_questi_categor_4dd374_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answerchoice",
            unique_together={("question", "order")},
        ),
        migrations.AddIndex(
            model_name="roadsign",
            index=models.Index(
                fields=["category"], name="core_roadsi_categor_f3eec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsign",
            index=models.Index(fields=["code"], name="core_roadsi_code_ea8443_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roadsigncategorytranslation",
            unique_together={("category", "language")},
        ),
        migrations.AddIndex(
            model_name="roadsigntranslation",
            index=models.Index(
                fields=["road_sign", "language"], name="core_roadsi_road_si_42c138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsigntranslation",
            index=models.Index(fields=["name"], name="core_roadsi_name_34697b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="roadsigntranslation",
            unique_together={("road_sign", "language")},
        ),
    ]
