# Generated by Django 5.2.8 on 2026-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_question_media_image_alter_roadsign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="unique",
            field=models.BooleanField(
                default=False,
                help_text="If true, can only be used in one exam",
                verbose_name="Unique",
            ),
        ),
    ]
