# Generated by Django 5.2.8 on 2025-12-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examtranslation",
            options={
                "verbose_name": "Exam Translation",
                "verbose_name_plural": "Exam Translations",
            },
        ),
        migrations.AlterUniqueTogether(
            name="examtranslation",
            unique_together={("exam", "language")},
        ),
    ]
