# Generated by Django 5.2.8 on 2025-12-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bundledefinition_recommended"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("MOBILE_WALLET", "Mobile Wallet"),
                    ("other", "Other Method"),
                ],
                default="MOBILE_WALLET",
            ),
        ),
        migrations.AlterField(
            model_name="bundledefinition",
            name="recommended",
            field=models.BooleanField(default=False, verbose_name="Recommended"),
        ),
    ]
