# Generated by Django 5.2.8 on 2026-01-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_examtranslation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
