# Generated by Django 5.2.8 on 2026-02-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_question_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="unique",
            field=models.BooleanField(
                default=True,
                help_text="If true, can only be used in one exam",
                verbose_name="Unique",
            ),
        ),
    ]
