# Generated by Django 5.2.8 on 2026-02-11 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_question_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="examtranslation",
            unique_together={("exam", "language", "title")},
        ),
    ]
