# Generated by Django 5.2.8 on 2026-03-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_exam_created_at_exam_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answerchoice",
            unique_together=set(),
        ),
    ]
