# Generated by Django 5.2.8 on 2026-01-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_examattempt_score"),
        ("users", "0007_remove_subscription_users_subsc_user_pr_a76397_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["deleted_at"], name="core_examat_deleted_f5c08b_idx"
            ),
        ),
    ]
