# Generated by Django 5.2.8 on 2026-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_answerchoice_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
