# Generated by Django 5.2.8 on 2026-01-05 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_subscriptiontier_exams"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, help_text="A valid logo url", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("MOBILE_WALLET", "Mobile Wallet"),
                            ("other", "Other Method"),
                        ],
                        default="MOBILE_WALLET",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethodTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("am", "Amharic"),
                            ("ti", "Tigrigna"),
                            ("or", "Afan Oromo"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("account_details", models.TextField(verbose_name="Account Details")),
                ("instruction", models.TextField(verbose_name="Instruction")),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="payment.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method Translation",
                "verbose_name_plural": "Payment Method Translations",
                "ordering": ["language"],
                "unique_together": {("payment_method", "language")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("account_last_5", models.CharField(blank=True, max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payment.paymentmethod",
                    ),
                ),
                (
                    "subscription_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.subscriptiontier",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "indexes": [
                    models.Index(
                        fields=["user_profile", "status"],
                        name="payment_tra_user_pr_2c1a34_idx",
                    )
                ],
            },
        ),
    ]
