# Generated by Django 5.2.8 on 2026-01-11 21:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="screenshot",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="User-uploaded payment proof screenshot",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
