# Generated by Django 5.2.8 on 2026-01-11 23:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_transaction_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account_last_5",
            field=models.CharField(
                blank=True,
                help_text="Last 5 digits of payer account (optional)",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Bank/mobile wallet transaction reference (optional if screenshot is provided)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="screenshot",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Screenshot of payment proof (alternative to reference number)",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
