# Generated by Django 5.2.8 on 2026-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_transaction_payer_name_transaction_payer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("MOBILE_WALLET", "Mobile Wallet"),
                    ("other", "Other Method"),
                ],
                default="MOBILE_WALLET",
                max_length=20,
            ),
        ),
    ]
